In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../datasets/balloons.csv')

In [3]:
df

color   size      act    age inflated
0   YELLOW  SMALL  STRETCH  ADULT        T
1   YELLOW  SMALL  STRETCH  ADULT        T
2   YELLOW  SMALL  STRETCH  ADULT        T
3   YELLOW    NaN  STRETCH  ADULT        T
4   YELLOW  SMALL  STRETCH  ADULT        T
..     ...    ...      ...    ...      ...
95  PURPLE  LARGE      DIP  CHILD        F
96  PURPLE  LARGE      DIP  CHILD        F
97  PURPLE  LARGE      DIP  CHILD        F
98  PURPLE  LARGE      DIP  CHILD        F
99  PURPLE  LARGE      DIP  CHILD        F

[100 rows x 5 columns]

In [4]:
df.isna().any()

color       False
size         True
act          True
age          True
inflated    False
dtype: bool

In [5]:
df.isna().sum()

color       0
size        1
act         1
age         1
inflated    0
dtype: int64

In [6]:
df.dropna(axis=0, inplace=True)

In [7]:
df.isna().sum()

color       0
size        0
act         0
age         0
inflated    0
dtype: int64

In [8]:
df.shape

(97, 5)

In [9]:
Y = df['inflated']
X = df.drop('inflated', axis=1)

In [10]:
feature_names = X.columns

In [11]:
feature_names

Index(['color', 'size', 'act', 'age'], dtype='object')

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=123, test_size=0.25, stratify=Y)

In [14]:
from sklearn.preprocessing import OrdinalEncoder

In [15]:
encoder = OrdinalEncoder()

In [16]:
encoder.fit(X_train)

OrdinalEncoder()

In [17]:
X_train = encoder.transform(X_train)

In [18]:
X_train

array([[1., 1., 0., 2.],
       [1., 1., 1., 0.],
       [1., 1., 0., 2.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 1., 2.],
       [0., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 2.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 2.],
       [1., 1., 1., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 2.],
       [0., 0., 1., 2.],
       [1., 0., 1., 2.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 2.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 1., 2.],
       [1., 0., 1., 2.],
       [0., 1., 0., 2.],
       [0., 1., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 2.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 2.],
       [1., 0., 0., 2.],


In [19]:
X_test = encoder.transform(X_test)

In [20]:
from sklearn.naive_bayes import CategoricalNB

In [21]:
model = CategoricalNB()

In [22]:
model.fit(X_train, y_train)

CategoricalNB()

In [23]:
y_train_pred = model.predict(X_train)

In [24]:
y_test_pred = model.predict(X_test)

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

In [26]:
confusion_matrix(y_train, y_train_pred)

array([[43,  1],
       [ 0, 28]])

In [27]:
accuracy_score(y_train, y_train_pred)

0.9861111111111112

In [31]:
confusion_matrix(y_test, y_test_pred)

array([[15,  0],
       [ 0, 10]])

In [32]:
accuracy_score(y_test, y_test_pred)

1.0